### ISSUE TITLE
ModuleNotFoundError: No module named 'nodepyrunner'

### ISSUE THREAD

**Issue by lzio** [supercoderlee/pycore-quick-start#2]
所有流程都已跑通，直到解注，请问这个模块无法安装和导入的原因是什么

**Comment by hileez** [comment]
@lzio nodepyrunner是node-pyrunner的内置模块，用于python与JavaScript交互，它既不是python标准模块也不是pip第三方模块，只有使用node-pyrunner去执行python脚本才能使用该模块。如果你需要在pycharm等IDE工具debug脚本，建议先注释掉nodepyrunner模块的有关代码。
